2019-12-12 20:07:56,097 ERROR: Exception on /edit_profile [GET] [in c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\routes.py", line 98, in edit_profile
    form = EditProfileForm()
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2019-12-12 20:11:17,359 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:45]
2019-12-12 20:11:30,774 ERROR: Exception on /index [GET] [in c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\routes.py", line 30, in index
    posts = current_user.followed_posts().paginate(
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\models.py", line 58, in followed_posts
    followers, (followers.c.followed_id == Post.user_id)).filter(
NameError: name 'followers' is not defined
2019-12-12 20:11:39,277 ERROR: Exception on /index [GET] [in c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\routes.py", line 30, in index
    posts = current_user.followed_posts().paginate(
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\models.py", line 58, in followed_posts
    followers, (followers.c.followed_id == Post.user_id)).filter(
NameError: name 'followers' is not defined
2019-12-12 20:29:42,878 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:43]
2019-12-12 20:45:39,083 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:43]
2019-12-12 21:09:40,005 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:45]
2019-12-12 21:10:27,297 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:45]
2019-12-12 21:13:22,444 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:45]
2019-12-12 21:15:18,809 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:45]
2019-12-12 22:20:39,153 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:45]
2019-12-12 22:31:11,351 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:45]
2019-12-12 22:34:28,007 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:45]
